app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
  contact: http://www.github.com/jntakpe/mformonitoring
  license: MIT
  licenseUrl: http://opensource.org/licenses/MIT
proxy:
  url: proxy.bforbank.gca
  port: 8080
  user: ntakpe_j
  password: juststfu31*
  workstation: SEL0000613426
  domain: sel.local
  byPassProxy:
  - "https://assemblage-lemon.dev.bforbank.gca/"
  - "localhost"
  - "127.0.0.1"
management:
  context-path: /manage
web:
  timeout: 5000
---
spring:
  profiles: dev
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:file:~/mfm;DB_CLOSE_DELAY=-1
    databaseName:
    serverName:
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
        ddl-auto: validate
server:
  port: 7080