app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
  contact: http://www.github.com/jntakpe/mformonitoring
  license: MIT
  licenseUrl: http://opensource.org/licenses/MIT
proxy:
  url: proxy
  port: 8080
  user: user_windows
  password: pass_windows
  workstation: nom_poste_travail
  domain: emeaad
  byPassProxy:
  - "https://proxy.corp.../"
  - "localhost"
  - "127.0.0.1"
management:
  context-path: /manage
web:
  timeout: 5000
---
spring:
  profiles: dev
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:file:~/mfm;DB_CLOSE_DELAY=-1
    databaseName:
    serverName:
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
        ddl-auto: update
server:
  port: 7080
