app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
  contact: http://www.github.com/jntakpe/mformonitoring
  license: MIT
  licenseUrl: http://opensource.org/licenses/MIT
management:
  context-path: /manage
web:
  timeout: 2000
---
spring:
  profiles: dev
  data:
    mongodb:
      database: mfm
server:
  port: 8080